server:
  port: 8080

spring:
  application:
    name: movies
  data:
    mongodb:
      uri: mongodb+srv://${env.MONGO_USER}:${env.MONGO_PASSWORD}@${env.MONGO_CLUSTER}/?tls=true
      database: ${env.MONGO_DB}